### ISSUE TITLE
Battery charge indication

### ISSUE THREAD

**Issue by VBIralo** [samdenty/Wi-PWN#21]
Can you add a battery charge indication to the Control Panel?

**Comment by br0k3nilluzion** [comment]
^^ that is a really good idea

**Comment by VBIralo** [comment]
I can give a little code))

**Comment by samdenty99** [comment]
I'm not actively developing Wi-PWN at the moment, I may continue in a few weeks (it depends though)

**Comment by StijnSimons** [comment]
@VBIralo If you want to help out, you can send a pull request! 😉

**Comment by VBIralo** [comment]
@StijnSimons I would, but I'm not very good at this. Good luck with the project! I appreciate your work! Thank you!

**Comment by VBIralo** [comment]
Here, on line 148, battery voltage measurement is used -> https://goo.gl/UpTYxy

**Comment by ExploiTR** [comment]
`ADC_MODE(ADC_VCC);` on top of everything in xxxxx_deauther.ino

`ESP.getVcc()` anywhere

http://esp8266.github.io/Arduino/versions/2.0.0-rc2/doc/libraries.html

**Comment by Eric00x** [comment]
But there's a big problem with voltages since A0 port can support max 3.3V (in older esps it's even like 1V) and batteries (li-pos or other kinds) usually have more than 3.3V on output when fully charged.
You'll have to put voltage divider before connecting battery's power to ESP or else it will cook by itself

**Comment by StijnSimons** [comment]
Closing because of compatibility issues.
